-- 📍 Page 1: Industry Overview
Total AUM = SUM(aum[AUM])
Total SIP Inflows = SUM(sip[Inflow])
Total Folios = SUM(folios[Count])
Total Schemes = COUNTROWS(schemes)

Industry AUM Trend = SUMMARIZE(aum, aum[Date], "TotalAUM", SUM(aum[AUM]))
AUM by AMC = SUMMARIZE(aum, aum[AMC], "TotalAUM", SUM(aum[AUM]))

-- 📍 Page 2: Fund Performance
Return = AVERAGE(fund_performance[Return])
Risk = STDEV.P(fund_performance[Return])
Fund Score = DIVIDE([Return], [Risk])

NAV vs Benchmark = 
SUMMARIZE(fund_nav, fund_nav[Date], 
          "FundNAV", SUM(fund_nav[NAV]), 
          "Benchmark", SUM(fund_nav[Benchmark]))

-- 📍 Page 3: Investor Analytics
Txn by State = SUMMARIZE(transactions, transactions[State], "Amount", SUM(transactions[Amount]))
Txn Split = SUMMARIZE(transactions, transactions[Type], "Amount", SUM(transactions[Amount]))
Avg SIP by Age = AVERAGEX(FILTER(transactions, transactions[Type] = "SIP"), transactions[Amount])
Monthly Volume = SUMMARIZE(transactions, transactions[Date], "TxnCount", COUNTROWS(transactions))

-- 📍 Page 4: SIP & Market Trends
SIP Inflow = SUM(sip[Inflow])
Nifty Trend = SUM(market[Nifty50])

Category Heatmap = SUMMARIZE(sip, sip[Category], "NetInflow", SUM(sip[Inflow]))
Top 5 Categories = TOPN(5, Category Heatmap, [NetInflow], DESC)
